USE PROJETO1;

SELECT  NOME_COMPLETO,
        TITULO_DA_DISSERTACAO_TESE
FROM    DOCENTE D
        INNER JOIN DOUTORADO T
        ON    D.DOCENTE_ID = T.DOCENTE_ID
WHERE   T.NOME_INSTITUICAO = "UNICAMP" AND D.SEXO = "F";


SELECT  NOME_COMPLETO,
        TITULO AS LINHA_DE_PESQUISA,
        T.NUM_PREMIOS AS NUM_PREMIOS
FROM    DOCENTE D
        INNER JOIN LINHA_DE_PESQUISA L
        ON    D.DOCENTE_ID = L.DOCENTE_ID
        INNER JOIN (
                    SELECT COUNT(*) AS NUM_PREMIOS,
									E.DOCENTE_ID
                    FROM   DOCENTE E
                           INNER JOIN PREMIO_TITULO P
                           ON    E.DOCENTE_ID = P.DOCENTE_ID
					GROUP BY P.DOCENTE_ID
                    ) T
        ON     D.DOCENTE_ID = T.DOCENTE_ID
WHERE   T.NUM_PREMIOS > 10
ORDER BY T.NUM_PREMIOS;


SELECT  NOME_COMPLETO,
        T.NOME_INSTITUICAO
FROM    DOCENTE D
        INNER JOIN DOUTORADO T
        ON    D.DOCENTE_ID = T.DOCENTE_ID
        INNER JOIN MESTRADO M
        ON    D.DOCENTE_ID = M.DOCENTE_ID
        INNER JOIN GRADUACAO G
        ON    D.DOCENTE_ID = G.DOCENTE_ID
WHERE   T.NOME_INSTITUICAO = M.NOME_INSTITUICAO AND T.NOME_INSTITUICAO = G.NOME_INSTITUICAO
ORDER BY NOME_COMPLETO;

SELECT  D.NOME_COMPLETO AS NOME_DOCENTE,
        T.NOME AS NOME_PROJETO,
        T.NOME_COMPLETO AS NOME_INTEGRANTE
FROM    DOCENTE D
        INNER JOIN (
                    SELECT  NOME,
                            NOME_COMPLETO,
                            DOCENTE_ID AS ID,
                            ANO_INICIO
                    FROM    PROJETO_DE_PESQUISA P
                            INNER JOIN INTEGRANTE_DO_PROJETO I
                            ON P.PROJETO_ID = I.PROJETO_ID
                    ORDER BY NOME
                    ) T
        ON          D.DOCENTE_ID = T.ID
WHERE SEXO = "F" AND T.ANO_INICIO > CURDATE();


-- SELECT  
