-- -----------------------------------------------------
-- Schema PROJETO1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROJETO1` DEFAULT CHARACTER SET utf8 ;
USE `PROJETO1` ;

-- -----------------------------------------------------
-- Table `PROJETO1`.`DOCENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`DOCENTE` (
  `DOCENTE_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_COMPLETO` VARCHAR(300) NOT NULL,
  `NOME_EM_CITACOES_BIBLIOGRAFICAS` VARCHAR(2000) NULL,
  `NACIONALIDADE` VARCHAR(100) NULL,
  `PAIS_DE_NASCIMENTO` VARCHAR(50) NULL,
  `UF_NASCIMENTO` VARCHAR(50) NULL,
  `CIDADE_NASCIMENTO` VARCHAR(50) NULL,
  `DATA_FALECIMENTO` VARCHAR(20) NULL,
  `SIGLA_PAIS_NACIONALIDADE` VARCHAR(5) NULL,
  `PAIS_DE_NACIONALIDADE` VARCHAR(100) NULL,
  `SEXO` VARCHAR(1) NULL,
  PRIMARY KEY (`DOCENTE_ID`),
  UNIQUE INDEX `NOME_COMPLETO_UNIQUE` (`NOME_COMPLETO` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`ATUACAO_PROFISSIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`ATUACAO_PROFISSIONAL` (
  `ATUACAO_PROFISSIONAL_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_INSTITUICAO` VARCHAR(100) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ATUACAO_PROFISSIONAL_ID`),
  INDEX `fk_ATUACAO-PROFISSIONAL_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_ATUACAO-PROFISSIONAL_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`ARTIGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`ARTIGO` (
  `ARTIGO_ID` INT NOT NULL AUTO_INCREMENT,
  `SITUACAO` VARCHAR(300) NULL,
  `TITULO` VARCHAR(300) NULL,
  `ANO_DO_ARTIGO` INT NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ARTIGO_ID`),
  INDEX `fk_DADOS-BASICOS-DO-ARTIGO_DOCENTE2_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_DADOS-BASICOS-DO-ARTIGO_DOCENTE2`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`DISCIPLINA` (
  `DISCIPLINA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(300) NULL,
  `TIPO_ENSINO` VARCHAR(300) NULL,
  `NOME_CURSO` VARCHAR(150) NULL,
  `NOME_INSTITUICAO` VARCHAR(300) NULL,
  `FLAG_PERIODO` VARCHAR(8) NULL,
  `MES_INICIO` INT NULL,
  `ANO_INICIO` INT NULL,
  `MES_FIM` INT NULL,
  `ANO_FIM` INT NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`DISCIPLINA_ID`),
  INDEX `fk_DISCIPLINA_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_DISCIPLINA_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`DOUTORADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`DOUTORADO` (
  `DOUTORADO_ID` INT NOT NULL AUTO_INCREMENT,
  `NIVEL` INT NULL,
  `NOME_INSTITUICAO` VARCHAR(150) NULL,
  `NOME_ORGAO` VARCHAR(150) NULL,
  `NOME_CURSO` VARCHAR(150) NULL,
  `STATUS_DO_CURSO` VARCHAR(50) NULL,
  `ANO_DE_INICIO` INT NULL,
  `ANO_DE_CONCLUSAO` INT NULL,
  `FLAG_BOLSA` VARCHAR(3) NULL,
  `NOME_AGENCIA` VARCHAR(150) NULL,
  `ANO_DE_OBTENCAO_DO_TITULO` INT NULL,
  `TITULO_DA_DISSERTACAO_TESE` VARCHAR(500) NULL,
  `NOME_COMPLETO_DO_ORIENTADOR` VARCHAR(150) NULL,
  `TIPO_DOUTORADO` VARCHAR(50) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`DOUTORADO_ID`),
  INDEX `fk_DOUTORADO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_DOUTORADO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`ENDERECO` (
  `ENDERECO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_INSTITUICAO_EMPRESA` VARCHAR(300) NULL,
  `NOME_ORGAO` VARCHAR(300) NULL,
  `DEPARTAMENTO` VARCHAR(300) NULL,
  `LOGRADOURO_COMPLEMENTO` VARCHAR(300) NULL,
  `PAIS` VARCHAR(300) NULL COMMENT '		',
  `UF` VARCHAR(25) NULL,
  `CEP` VARCHAR(25) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `BAIRRO` VARCHAR(300) NULL,
  `DDD` VARCHAR(3) NULL,
  `TELEFONE` VARCHAR(10) NULL,
  `FAX` VARCHAR(10) NULL,
  `CAIXA_POSTAL` VARCHAR(10) NULL,
  `HOME_PAGE` VARCHAR(150) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ENDERECO_ID`),
  INDEX `fk_ENDERECO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_ENDERECO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`PROJETO_DE_PESQUISA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`PROJETO_DE_PESQUISA` (
  `PROJETO_ID` INT NOT NULL AUTO_INCREMENT,
  `ANO_INICIO` INT NULL,
  `ANO_FIM` INT NULL,
  `NOME` VARCHAR(300) NULL,
  `SITUACAO` VARCHAR(300) NULL,
  `NATUREZA` VARCHAR(300) NULL,
  `DESCRICAO` VARCHAR(4000) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`PROJETO_ID`),
  INDEX `fk_PROJETO-DE-PESQUISA_DOCENTE2_idx` (`DOCENTE_ID` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC),
  CONSTRAINT `fk_PROJETO-DE-PESQUISA_DOCENTE2`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`FINANCIADOR_DO_PROJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`FINANCIADOR_DO_PROJETO` (
  `FINANCIADOR_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_INSTITUICAO` VARCHAR(300) NULL,
  `NATUREZA` VARCHAR(150) NULL,
  `PROJETO_ID` INT NOT NULL,
  PRIMARY KEY (`FINANCIADOR_ID`),
  INDEX `fk_FINANCIADOR-DO-PROJETO_PROJETO-DE-PESQUISA1_idx` (`PROJETO_ID` ASC),
  UNIQUE INDEX `FINANCIA_PROJETO` (`NOME_INSTITUICAO` ASC, `PROJETO_ID` ASC),
  CONSTRAINT `fk_FINANCIADOR-DO-PROJETO_PROJETO-DE-PESQUISA1`
    FOREIGN KEY (`PROJETO_ID`)
    REFERENCES `PROJETO1`.`PROJETO_DE_PESQUISA` (`PROJETO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`GRADUACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`GRADUACAO` (
  `GRADUACAO_ID` INT NOT NULL AUTO_INCREMENT,
  `NIVEL` INT NULL,
  `TITULO_TCC` VARCHAR(500) NULL,
  `NOME_DO_ORIENTADOR` VARCHAR(150) NULL,
  `NOME_INSTITUICAO` VARCHAR(150) NULL,
  `NOME_ORGAO` VARCHAR(50) NULL,
  `NOME_CURSO` VARCHAR(150) NULL,
  `STATUS_DO_CURSO` VARCHAR(50) NULL,
  `ANO_DE_INICIO` INT NULL,
  `ANO_DE_CONCLUSAO` INT NULL,
  `FLAG_BOLSA` VARCHAR(3) NULL,
  `NOME_AGENCIA` VARCHAR(300) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`GRADUACAO_ID`),
  INDEX `fk_GRADUACAO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_GRADUACAO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`IDIOMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`IDIOMA` (
  `IDIOMA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(30) NULL,
  `DESCRICAO` VARCHAR(300) NULL,
  `PROFICIENCIA_DE_LEITURA` VARCHAR(300) NULL,
  `PROFICIENCIA_DE_FALA` VARCHAR(1000) NULL,
  `PROFICIENCIA_DE_ESCRITA` VARCHAR(300) NULL,
  `PROFICIENCIA_DE_COMPREENSAO` VARCHAR(300) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`IDIOMA_ID`),
  INDEX `fk_IDIOMA_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_IDIOMA_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`INTEGRANTE_DO_PROJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`INTEGRANTE_DO_PROJETO` (
  `INTEGRANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_COMPLETO` VARCHAR(200) NULL,
  `NOME_PARA_CITACAO` VARCHAR(1000) NULL,
  `FLAG_RESPONSAVEL` VARCHAR(3) NULL,
  `PROJETO_ID` INT NOT NULL,
  PRIMARY KEY (`INTEGRANTE_ID`),
  INDEX `fk_INTEGRANTES-DO-PROJETO_PROJETO-DE-PESQUISA1_idx` (`PROJETO_ID` ASC),
  UNIQUE INDEX `PARTICIPA_PROJETO` (`NOME_COMPLETO` ASC, `PROJETO_ID` ASC),
  CONSTRAINT `fk_INTEGRANTES-DO-PROJETO_PROJETO-DE-PESQUISA1`
    FOREIGN KEY (`PROJETO_ID`)
    REFERENCES `PROJETO1`.`PROJETO_DE_PESQUISA` (`PROJETO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`LINHA_DE_PESQUISA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`LINHA_DE_PESQUISA` (
  `LINHA_DE_PESQUISA_ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(150) NULL,
  `FLAG_ATIVA` VARCHAR(3) NULL,
  `OBJETIVOS` VARCHAR(2500) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`LINHA_DE_PESQUISA_ID`),
  INDEX `fk_LINHA-DE-PESQUISA_DOCENTE2_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_LINHA-DE-PESQUISA_DOCENTE2`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`MESTRADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`MESTRADO` (
  `MESTRADO_ID` INT NOT NULL AUTO_INCREMENT,
  `NIVEL` INT NULL,
  `NOME_INSTITUICAO` VARCHAR(150) NULL,
  `NOME_ORGAO` VARCHAR(150) NULL,
  `NOME_CURSO` VARCHAR(150) NULL,
  `STATUS_DO_CURSO` VARCHAR(50) NULL,
  `ANO_DE_INICIO` INT NULL,
  `ANO_DE_CONCLUSAO` INT NULL,
  `FLAG_BOLSA` VARCHAR(3) NULL,
  `NOME_AGENCIA` VARCHAR(150) NULL,
  `ANO_DE_OBTENCAO_DO_TITULO` INT NULL,
  `TITULO_DA_DISSERTACAO_TESE` VARCHAR(500) NULL,
  `NOME_COMPLETO_DO_ORIENTADOR` VARCHAR(150) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`MESTRADO_ID`),
  INDEX `fk_MESTRADO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_MESTRADO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`ORIENTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`ORIENTACAO` (
  `ORIENTACAO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(300) NULL,
  `TITULO` VARCHAR(300) NULL,
  `ANO` INT NULL,
  `PAIS` VARCHAR(300) NULL,
  `IDIOMA` VARCHAR(300) NULL,
  `NOME_DO_ORIENTADO` VARCHAR(300) NULL,
  `SITUACAO` VARCHAR(45) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ORIENTACAO_ID`),
  INDEX `fk_ORIENTACOES_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_ORIENTACOES_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`BANCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`BANCA` (
  `BANCA_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(50) NULL,
  `TITULO` VARCHAR(300) NULL,
  `ANO` INT NULL,
  `PAIS` VARCHAR(30) NULL,
  `IDIOMA` VARCHAR(30) NULL,
  `NOME_DO_CANDIDATO` VARCHAR(150) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`BANCA_ID`),
  INDEX `fk_BANCAS_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_BANCAS_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`POS_DOUTORADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`POS_DOUTORADO` (
  `POS_DOUTORADO_ID` INT NOT NULL AUTO_INCREMENT,
  `NIVEL` INT NULL,
  `NOME_INSTITUICAO` VARCHAR(150) NULL,
  `ANO_DE_INICIO` INT NULL,
  `ANO_DE_CONCLUSAO` INT NULL,
  `ANO_DE_OBTENCAO_DO_TITULO` INT NULL,
  `FLAG_BOLSA` VARCHAR(3) NULL,
  `NOME_AGENCIA` VARCHAR(150) NULL,
  `STATUS_DO_ESTAGIO` VARCHAR(50) NULL,
  `STATUS_DO_CURSO` VARCHAR(50) NULL,
  `TITULO_DO_TRABALHO` VARCHAR(500) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`POS_DOUTORADO_ID`),
  INDEX `fk_POS-DOUTORADO_DOCENTE1_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_POS-DOUTORADO_DOCENTE1`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`PREMIO_TITULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`PREMIO_TITULO` (
  `PREMIO_TITULO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(300) NULL,
  `ENTIDADE_PROMOTORA` VARCHAR(300) NULL,
  `ANO_DA_PREMIACAO` INT NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`PREMIO_TITULO_ID`),
  INDEX `fk_PREMIO-TITULO_DOCENTE2_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_PREMIO-TITULO_DOCENTE2`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PROJETO1`.`LIVRE_DOCENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJETO1`.`LIVRE_DOCENCIA` (
  `LIVRE_DOCENCIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NIVEL` INT NULL,
  `NOME_INSTITUICAO` VARCHAR(150) NULL,
  `ANO_DE_OBTENCAO_DO_TITULO` INT NULL,
  `TITULO_DO_TRABALHO` VARCHAR(150) NULL,
  `DOCENTE_ID` INT NOT NULL,
  PRIMARY KEY (`LIVRE_DOCENCIA_ID`),
  INDEX `fk_LIVRE-DOCENCIA_DOCENTE_idx` (`DOCENTE_ID` ASC),
  CONSTRAINT `fk_LIVRE-DOCENCIA_DOCENTE`
    FOREIGN KEY (`DOCENTE_ID`)
    REFERENCES `PROJETO1`.`DOCENTE` (`DOCENTE_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
