LOAD DATA INFILE 'file_name' IGNORE INTO TABLE ARTIGO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (SITUACAO,TITULO,ANO_DO_ARTIGO)
    SET   ARTIGO_ID =  NULL,
          DOCENTE_ID = id_docente;
