LOAD DATA INFILE 'file_name' IGNORE INTO TABLE DOCENTE
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NOME_COMPLETO,NOME_EM_CITACOES_BIBLIOGRAFICAS,NACIONALIDADE,PAIS_DE_NASCIMENTO,UF_NASCIMENTO,CIDADE_NASCIMENTO,DATA_FALECIMENTO,SIGLA_PAIS_NACIONALIDADE,PAIS_DE_NACIONALIDADE)
    SET   DOCENTE_ID = id_docente;
