LOAD DATA INFILE 'file_name' IGNORE INTO TABLE ENDERECO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NOME_INSTITUICAO_EMPRESA,NOME_ORGAO,DEPARTAMENTO,LOGRADOURO_COMPLEMENTO,PAIS,UF,CEP,CIDADE,BAIRRO,DDD,TELEFONE,FAX,CAIXA_POSTAL,HOME_PAGE)
    SET   ENDERECO_ID = NULL,
          DOCENTE_ID = id_docente;
