LOAD DATA INFILE 'file_name' IGNORE INTO TABLE GRADUACAO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NIVEL,TITULO_TCC,NOME_DO_ORIENTADOR,NOME_INSTITUICAO,NOME_ORGAO,NOME_CURSO,STATUS_DO_CURSO,ANO_DE_INICIO,ANO_DE_CONCLUSAO,FLAG_BOLSA,NOME_AGENCIA)
    SET   GRADUACAO_ID = NULL,
          DOCENTE_ID = id_docente;
