-- Inserindo o sexo de cada Docente manualmente

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 1;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 2;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 3;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 4;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 5;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 6;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 7;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 8;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 9;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 10;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 11;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 12;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 13;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 14;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 15;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 16;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 17;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 18;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 19;

UPDATE IGNORE DOCENTE
SET SEXO =  'M'
WHERE DOCENTE_ID = 20;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 21;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 22;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 23;

UPDATE IGNORE DOCENTE
SET SEXO =  'H'
WHERE DOCENTE_ID = 24;
