
CREATE TABLE TMP_TBL (
    TMP_PK_PROJ INT NOT NULL AUTO_INCREMENT,
    TMP_NOME_INSTITUICAO VARCHAR(150) NULL,
    TMP_NATUREZA VARCHAR(150) NULL,
    TMP_FK_FINANCIADOR VARCHAR(500) NOT NULL,
    TMP_NOME_COMPLETO VARCHAR(200) NULL,
    TMP_NOME_PARA_CITACAO VARCHAR(1000) NULL,
    TMP_FLAG_RESPONSAVEL VARCHAR(3) NULL,
    TMP_FK_INTEGRANTE VARCHAR(1000) NOT NULL,
    PRIMARY KEY (TMP_PK_PROJ) )
  DEFAULT CHARACTER SET = utf8;


LOAD DATA LOCAL INFILE 'file_name' INTO TABLE TMP_TBL
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 LINES
    (TMP_NOME_COMPLETO, TMP_NOME_PARA_CITACAO, TMP_FLAG_RESPONSAVEL, TMP_FK_INTEGRANTE);

INSERT IGNORE INTO INTEGRANTE_DO_PROJETO (NOME_COMPLETO, NOME_PARA_CITACAO, FLAG_RESPONSAVEL, PROJETO_ID)
SELECT TMP_NOME_COMPLETO, TMP_NOME_PARA_CITACAO, TMP_FLAG_RESPONSAVEL, PROJETO_DE_PESQUISA.PROJETO_ID
FROM TMP_TBL, PROJETO_DE_PESQUISA
WHERE TMP_FK_INTEGRANTE = PROJETO_DE_PESQUISA.NOME;

DROP TABLE TMP_TBL;
