LOAD DATA INFILE 'file_name' IGNORE INTO TABLE LINHA_DE_PESQUISA
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (TITULO,FLAG_ATIVA,OBJETIVOS)
    SET   LINHA_DE_PESQUISA_ID = NULL,
          DOCENTE_ID = id_docente;
