LOAD DATA INFILE 'file_name' IGNORE INTO TABLE LIVRE_DOCENCIA
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NIVEL,NOME_INSTITUICAO,ANO_DE_OBTENCAO_DO_TITULO,TITULO_DO_TRABALHO)
    SET   LIVRE_DOCENCIA_ID = NULL,
          DOCENTE_ID = id_docente;
