LOAD DATA INFILE 'file_name' IGNORE INTO TABLE MESTRADO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NIVEL,NOME_INSTITUICAO,NOME_ORGAO,NOME_CURSO,STATUS_DO_CURSO,ANO_DE_INICIO,ANO_DE_CONCLUSAO,FLAG_BOLSA,NOME_AGENCIA,ANO_DE_OBTENCAO_DO_TITULO,TITULO_DA_DISSERTACAO_TESE,NOME_COMPLETO_DO_ORIENTADOR)
    SET   MESTRADO_ID = NULL,
          DOCENTE_ID = id_docente;
