LOAD DATA INFILE 'file_name' IGNORE INTO TABLE ORIENTACAO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (TIPO,TITULO,ANO,PAIS,IDIOMA,NOME_DO_ORIENTADO)
    SET   ORIENTACAO_ID = NULL,
          SITUACAO = 'EM ANDAMENTO',
          DOCENTE_ID = id_docente;
