LOAD DATA INFILE 'file_name' IGNORE INTO TABLE BANCA
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (TIPO,TITULO,ANO,PAIS,IDIOMA,NOME_DO_CANDIDATO)
    SET   BANCA_ID = NULL,
          DOCENTE_ID = id_docente;
