LOAD DATA INFILE 'file_name' IGNORE INTO TABLE POS_DOUTORADO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NIVEL,NOME_INSTITUICAO,ANO_DE_INICIO,ANO_DE_CONCLUSAO,ANO_DE_OBTENCAO_DO_TITULO,FLAG_BOLSA,NOME_AGENCIA,STATUS_DO_ESTAGIO,STATUS_DO_CURSO,TITULO_DO_TRABALHO)
    SET   POS_DOUTORADO_ID = NULL,
          DOCENTE_ID = id_docente;
