LOAD DATA INFILE 'file_name' IGNORE INTO TABLE PREMIO_TITULO
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (NOME,ENTIDADE_PROMOTORA,ANO_DA_PREMIACAO)
    SET   PREMIO_TITULO_ID = NULL,
          DOCENTE_ID = id_docente;
