LOAD DATA INFILE 'file_name' IGNORE INTO TABLE PROJETO_DE_PESQUISA
    CHARACTER SET utf8
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\r\n'
    IGNORE 1 LINES
    (ANO_INICIO,ANO_FIM,NOME,SITUACAO,NATUREZA,DESCRICAO)
    SET   PROJETO_ID = NULL,
          DOCENTE_ID = id_docente;
